apiVersion: v1
kind: Service
metadata:
  name: mydb
  labels:
    app: mydb
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mydb

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mydb
spec:
  selector:
    matchLabels:
      app: mydb
  serviceName: "mydb"
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mydb
        image: yunjun2/mydb:1.0.1
        ports:
        - containerPort: 3306
      volumes:
      - name: myvol
        emptyDir: {}
